language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true

install:
  - sudo apt-get update
  - sudo apt-get install python-qt4
  - pip install gevent Flask lxml SOAPpy
  - python setup.py install
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: tests/run_test.py -v